# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/os/CLionProjects/untitled3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/os/CLionProjects/untitled3/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/os/CLionProjects/untitled3/build/CMakeFiles /home/os/CLionProjects/untitled3/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/os/CLionProjects/untitled3/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clinic_management_system

# Build rule for target.
clinic_management_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clinic_management_system
.PHONY : clinic_management_system

# fast build rule for target.
clinic_management_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/build
.PHONY : clinic_management_system/fast

Appointment.o: Appointment.cpp.o
.PHONY : Appointment.o

# target to build an object file
Appointment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/Appointment.cpp.o
.PHONY : Appointment.cpp.o

Appointment.i: Appointment.cpp.i
.PHONY : Appointment.i

# target to preprocess a source file
Appointment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/Appointment.cpp.i
.PHONY : Appointment.cpp.i

Appointment.s: Appointment.cpp.s
.PHONY : Appointment.s

# target to generate assembly for a file
Appointment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/Appointment.cpp.s
.PHONY : Appointment.cpp.s

Billing.o: Billing.cpp.o
.PHONY : Billing.o

# target to build an object file
Billing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/Billing.cpp.o
.PHONY : Billing.cpp.o

Billing.i: Billing.cpp.i
.PHONY : Billing.i

# target to preprocess a source file
Billing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/Billing.cpp.i
.PHONY : Billing.cpp.i

Billing.s: Billing.cpp.s
.PHONY : Billing.s

# target to generate assembly for a file
Billing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/Billing.cpp.s
.PHONY : Billing.cpp.s

ClinicManagementSystem.o: ClinicManagementSystem.cpp.o
.PHONY : ClinicManagementSystem.o

# target to build an object file
ClinicManagementSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/ClinicManagementSystem.cpp.o
.PHONY : ClinicManagementSystem.cpp.o

ClinicManagementSystem.i: ClinicManagementSystem.cpp.i
.PHONY : ClinicManagementSystem.i

# target to preprocess a source file
ClinicManagementSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/ClinicManagementSystem.cpp.i
.PHONY : ClinicManagementSystem.cpp.i

ClinicManagementSystem.s: ClinicManagementSystem.cpp.s
.PHONY : ClinicManagementSystem.s

# target to generate assembly for a file
ClinicManagementSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/ClinicManagementSystem.cpp.s
.PHONY : ClinicManagementSystem.cpp.s

Patient.o: Patient.cpp.o
.PHONY : Patient.o

# target to build an object file
Patient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/Patient.cpp.o
.PHONY : Patient.cpp.o

Patient.i: Patient.cpp.i
.PHONY : Patient.i

# target to preprocess a source file
Patient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/Patient.cpp.i
.PHONY : Patient.cpp.i

Patient.s: Patient.cpp.s
.PHONY : Patient.s

# target to generate assembly for a file
Patient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/Patient.cpp.s
.PHONY : Patient.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clinic_management_system.dir/build.make CMakeFiles/clinic_management_system.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clinic_management_system"
	@echo "... Appointment.o"
	@echo "... Appointment.i"
	@echo "... Appointment.s"
	@echo "... Billing.o"
	@echo "... Billing.i"
	@echo "... Billing.s"
	@echo "... ClinicManagementSystem.o"
	@echo "... ClinicManagementSystem.i"
	@echo "... ClinicManagementSystem.s"
	@echo "... Patient.o"
	@echo "... Patient.i"
	@echo "... Patient.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

